// POST TYPES
export const GET_POSTS = 'GET_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const RECEIVE_SINGLE_POST = 'RECEIVE_SINGLE_POST';
export const CREATE_POST = 'CREATE_POST';
export const EDIT_POST = 'EDIT_POST';
export const CHANGE_POST = 'CHANGE_POST';
export const CHANGE_ORDER = 'CHANGE_ORDER';

// CATEGORY TYPES
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const RECIEVE_CATEGORIES = 'RECIEVE_CATEGORIES';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';

// COMMENT TYPES
export const GET_COMMENTS = 'GET_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const RECEIVE_SINGLE_COMMENT = 'RECEIVE_SINGLE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
